services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AUS\GroupAccess\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  AUS\GroupAccess\EventListener\BeforeActionCallEventListener:
    tags:
      - name: event.listener
        identifier: 'group_access'
        event: TYPO3\CMS\Extbase\Event\Mvc\BeforeActionCallEvent
